
local Config = {
    Project = {
        Name = "NuruNuruRoll",
        SisterProject = "NuruNuruHill",
        DisplayTitle = "ぬるぬるHill ～街中ダウンヒル～",
        EnglishTitle = "NuruNuru Hill – Town Downhill",
        EnableStartRedBall = false,
        EnableDownhillController = false,
        EnableDownhillStartSystem = false,
        EnableGravitySlideController = false,
        EnableDownhillCamera = false,
        EnableDownhillJumpPhysics = false,
        EnableDownhillDebug = true,
        EnableDownhillMinimalMode = true,
        EnableDownhillProbeLogs = true,
        EnableDownhillClientImpulseProbe = false,
        EnableDownhillServerOwnershipProbe = false,
        EnableDownhillServerImpulseProbe = false,
        EnableLegacySledSystem = false,
        EnableLegacySledInput = false,
        EnableLegacySlideHud = false,
        EnableLegacyRoundSystem = false,
        EnableLegacyResultUi = false,
        EnableLegacyGoalSystem = false,
        EnableOfficialRacingRestore = true,
        EnableOfficialRacingClientProbe = true,

        BathVisualEnabled = true,
        BathDummyEnabled = true,
        HideOriginalCharacter = true,
        BathVisualUseRenderTracking = true,
        BathVisualDebugEnabled = true,

        OverviewCameraEnabled = true,
        OverviewCameraHoldKey = "Shift",
        OverviewCameraUseCourseBounds = true,

        EnableFixedR15RuntimeProbe = false,
        EnableLegacyCharacterPose = false,
        EnableLegacyCharacterSpin = false,
        EnableLegacySlideVisual = false,
        EnableLegacySlideCharacterController = false,
        EnableFixedR15VisualRig = false,
        HideRealCharacter = false,
        VisualRigStaticSpawnEnabled = false,
        VisualRigRequireVehicleSeat = false,
        VisualRigTrackingEnabled = false,
        VisualRigHeadingEnabled = false,
        VisualRigFixedPoseEnabled = false,
    },

    FixedR15VisualRig = {
        Enabled = true,
        VisualMinimumDirectionSpeed = 3,
        VisualHeightOffset = 2.0,
        VisualForwardOffset = 0,
        VisualSideOffset = 0,
        VisualHeadingResponse = 12,
    },

    BathVisual = {
        BathHeightOffset = -1.4,
        BathForwardOffset = 0,
        BathSideOffset = 0,

        BathYawOffsetDegrees = 0,
        BathPitchOffsetDegrees = 0,
        BathRollOffsetDegrees = 0,

        OldManHeadHeightOffset = 1.8,
        OldManTorsoHeightOffset = 0.4,
        OldManForwardOffset = 0.3,
        OldManSideOffset = 0,
        OldManArmHeightOffset = 1.0,
        OldManArmForwardOffset = 0.15,
    },

    OverviewCamera = {
        OverviewCameraFieldOfView = 60,
        OverviewCameraUseCourseBounds = true,
        OverviewCameraPadding = 1.35,

        OverviewCameraPitchDegrees = -55,
        OverviewCameraInitialYawDegrees = 0,
        OverviewRotationSpeedDegreesPerSecond = 55,

        OverviewCameraMinimumDistance = 700,
        OverviewCameraMaximumDistance = 5000,

        OverviewCameraTransitionSeconds = 0,
    },

    Round = {
        DurationSeconds = 90,
        IntermissionSeconds = 10,
    },

    Slide = {
        BaseSpeed = 4,
        JumpPower = 24,
        RacingMode = false,
        BodySlideEnabled = false,
        SlideBodyMode = false,
        BodyLeanAngle = 82,
        RideHeight = 3,
        GroundRayDistance = 35,
        GroundLostGraceTime = 0.5,
        MaxAllowedGroundDistance = 10,
        HardSnapGroundDistance = 20,
        MinSpeed = 45,
        MinSlideSpeed = 45,
        CruiseSpeed = 70,
        MaxSpeed = 140,
        MaxSlideSpeed = 140,
        Acceleration = 20,
        Deceleration = 10,
        VelocityLerpSpeed = 8,
        SteeringRate = 90,
        SteeringResponsiveness = 6,
        DriftAmount = 0.28,
        LateralDamping = 4,
        MaxLateralSpeed = 25,
        GroundFollowSpeed = 18,
        MaxGroundCorrectionSpeed = 70,
        OrientationResponsiveness = 10,
        OrientationMaxAngularVelocity = 10,
        AngularDamping = 0.15,
        SafePositionUpdateInterval = 0.2,
        ResetGraceTime = 1.0,
        FallResetY = 50,
        OffCourseGraceTime = 2.5,
        MaxDistanceFromCourse = 400,
        RespawnHeightOffset = 5,
        ResetSuppressSeconds = 0.45,
        ExitGraceSeconds = 0.45,
        CameraOffset = Vector3.new(0, -1.1, 1.6),
        CameraSpeedFovBoost = 10,
        Debug = false,
    },

    Goal = {
        PointsPerGoal = 100,
    },

    Sled = {
        Debug = true,
        MinSpeed = 42,
        CruiseSpeed = 72,
        MaxSpeed = 112,
        ThrottleBoost = 28,
        BrakeDeceleration = 62,
        BaseAcceleration = 36,
        SteeringPower = 1,
        SteeringYawRateDeg = 82,
        SteeringResponse = 8,
        LateralDamping = 3.2,
        SlopeAssist = 46,
        GroundRayDistance = 24,
        GroundedDistance = 2,
        NearGroundDistance = 8,
        MinSpeedRecoveryAccel = 60,
        StuckBoostAccel = 95,
        RespawnYMargin = 120,
        RespawnUnseatedSeconds = 2.5,
        RespawnStopSeconds = 3.5,
        RespawnTippedSeconds = 2.2,
        CountdownSeconds = 2,
    },

    Downhill = {
        StartSpeed = 24,
        MinimumGroundSpeed = 28,
        BaseTargetSpeed = 48,
        MaximumGroundSpeed = 125,

        DownhillSpeedBonus = 105,
        UphillSpeedPenalty = 55,

        GroundAcceleration = 36,
        GroundDeceleration = 22,
        LandingRecoveryAcceleration = 18,

        MaximumLateralSpeed = 24,
        GroundSteerAcceleration = 55,
        GroundSteerRelease = 22,
        AirSteerAcceleration = 12,

        ForwardCorrectionStrength = 5.5,
        MaximumForwardCorrectionAngle = 28,
        EdgeSafetyRatio = 0.84,
        EdgeReturnAcceleration = 48,

        GroundRayDistance = 7,
        GroundContactDistance = 4.5,
        GroundStickSpeed = 3.5,
        AirborneConfirmTime = 0.10,

        MinimumJumpSpeed = 35,
        LandingSoftImpactSpeed = 22,
        LandingHardImpactSpeed = 55,
        SoftLandingSpeedRetention = 0.96,
        HardLandingSpeedRetention = 0.78,

        WallCollisionCooldown = 0.35,
        WallSpeedRetention = 0.72,
        WallLateralRetention = 0.45,

        CameraBackOffset = 0.65,
        CameraUpOffset = 0.85,
        CameraLookAheadMin = 18,
        CameraLookAheadMax = 48,
        CameraPositionResponsiveness = 14,
        CameraRotationResponsiveness = 11,
        CameraBaseFov = 78,
        CameraMaximumFov = 96,
        CameraFovSpeedReference = 115,
        CameraMaximumRollDegrees = 6,
    },

    DownhillStart = {
        MapReadyTimeoutSeconds = 30,
        StartRequestCooldownSeconds = 0.75,
        MaximumStartDistance = 80,
        StartImpulseSpeed = 10,
        StartLaunchSpeed = 24,
        StartLaunchDownwardSpeed = -2,
        StartForwardOffsetStuds = 3,
        StartLaunchLinearVelocityDuration = 0.35,
        StartMotionCheckWindowSeconds = 0.5,
        StartMotionMinimumSpeed = 3,
        StartMotionRecoverySpeed = 18,
        WaitingWalkSpeed = 0,
        WaitingJumpPower = 0,
        SlidingWalkSpeed = 0,
        SlidingJumpPower = 0,
        OffCourseGraceSeconds = 3,
        RecoveryRayDistance = 60,
        MaximumSafeSpeed = 220,
        RespawnCooldownSeconds = 2,
    },

    GravitySlide = {
        GroundRayDistance = 12,
        GroundProbeHeight = 2,
        SlideGravityMultiplier = 1,
        SlideMinimumSpeed = 12,
        SlideFlatAssistAcceleration = 7,
        SlideFlatSlopeThreshold = 0.02,
        SlideRoadFriction = 0.02,
        SlideRoadFrictionWeight = 1,
        SteeringAcceleration = 42,
        LateralDamping = 3.4,
        RollingDeceleration = 1.6,
        MinimumAssistSpeed = 12,
        MinimumAssistAcceleration = 7,
        MaximumSpeed = 145,
        OverspeedBrakeAcceleration = 18,
        UphillThreshold = 0.015,
        AirSteeringScale = 0,
        CharacterDensity = 0.7,
        CharacterFriction = 0.05,
        CharacterElasticity = 0,
        Debug = true,
        DebugIntervalSeconds = 1,
    },

    Course = {
        ModelName = "NuruNuruCourse",
        StartHeight = 420,
        RepeatCount = 10,
        YawVariationDeg = 8,
        LengthVariationRatio = 0.1,
        CurveDensityMultiplier = 3,
        BumpHeightMultiplier = 3,

        -- Positive downDeg always goes downhill. bumpHeight adds a smooth hump on top.
        Segments = {
            { name = "StartDrop", length = 420, width = 87, downDeg = 20, yawDeg = 10 },
            { name = "HairpinRightA", length = 340, width = 84, downDeg = 16, yawDeg = 82 },
            { name = "SLeftA", length = 300, width = 82, downDeg = 18, yawDeg = -48 },
            { name = "SRightA", length = 300, width = 82, downDeg = 18, yawDeg = 54 },
            { name = "BumpJumpA", length = 220, width = 80, downDeg = 14, yawDeg = -20, bumpHeight = 22 },
            { name = "HairpinLeftA", length = 360, width = 82, downDeg = 16, yawDeg = -86 },
            { name = "SRightB", length = 320, width = 82, downDeg = 20, yawDeg = 46 },
            { name = "SLeftB", length = 320, width = 82, downDeg = 20, yawDeg = -50 },
            { name = "SteepDropA", length = 620, width = 84, downDeg = 26, yawDeg = 14 },
            { name = "BumpJumpB", length = 220, width = 80, downDeg = 15, yawDeg = 18, bumpHeight = 24 },
            { name = "HairpinRightB", length = 360, width = 84, downDeg = 18, yawDeg = 88 },
            { name = "SLeftC", length = 300, width = 82, downDeg = 20, yawDeg = -44 },
            { name = "SRightC", length = 300, width = 82, downDeg = 20, yawDeg = 46 },
            { name = "SteepDropB", length = 700, width = 86, downDeg = 28, yawDeg = -12 },
            { name = "HairpinLeftB", length = 360, width = 84, downDeg = 16, yawDeg = -84 },
            { name = "SRightD", length = 320, width = 84, downDeg = 22, yawDeg = 42 },
            { name = "SLeftD", length = 320, width = 84, downDeg = 22, yawDeg = -44 },
            { name = "FinalDrop", length = 920, width = 90, downDeg = 30, yawDeg = 8 },
            { name = "SeaDive", length = 360, width = 92, downDeg = 34, yawDeg = 0 },
        },
    },
}

return Config
